version: "3.8"

services:
  db:
    build: .
    container_name: purroute_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: purroute
      POSTGRES_USER: purroute
      POSTGRES_HOST_AUTH_METHOD: trust
#      POSTGRES_PASSWORD: purroute
#    volumes:
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
